name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
       submodules: 'true'   
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
       registry: ${{env.REGISTRY}}
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:v$(date +%s)
    - name: Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/amd64,linux/arm64,linux/arm
        tags: lifei6671/douyinbot:v$(date +%s)
